- src/type/array_composite.zig
- src/type/container.zig
- test/int/type/list_composite.zig
- for typescript, `serializeToBytes` returns absolute offset to the original DataView because there is no slice there and interface has to go with `DataView + offset`
- for zig, `serializeToBytes` is implemented in slice so it returns the number of bytes written, consumer need to accumulate it for correct offset
- also fix `readVariableOffsetsArrayComposite`, this is the same to typescript's implementation
> fix: serialization for Container and ArrayComposite

- src/type/bit_list.zig
- src/type/bit_vector.zig
- src/type/boolean.zig
- src/type/byte_list.zig
- src/type/byte_vector_type.zig
- src/type/container.zig
- src/type/list_basic.zig
- src/type/list_composite.zig
- src/type/uint.zig
- src/type/vector_basic.zig
- src/type/vector_composite.zig
- test/int/type/byte_list.zig
- test/int/type/container.zig
- test/int/type/list_basic.zig
- test/int/type/list_composite.zig
- test/int/type/vector_basic.zig
- test/int/type/vector_composite.zig
**Motivation**
- for typescript, to define a SSZ type it's pretty simple
```typescript
export const ValidatorType = {
pubkey: BLSPubkey,
withdrawalCredentials: Bytes32,
effectiveBalance: UintNum64,
slashed: Boolean,
activationEligibilityEpoch: EpochInf,
activationEpoch: EpochInf,
exitEpoch: EpochInf,
withdrawableEpoch: EpochInf,
};
```
based on that it uses `ValueOf` utility to infer Typescript type
- however for now in zig it has to define both ssz type and zig type
```zig
pub fn createContainerType(comptime ST: type, comptime ZT: type, hashFn: HashFn) type {
```
should be able to infer `ZT` from `ST` similar to typescript
- infer zig type `ZT` from `ST`
- each type needs to define `getZigType() type` and `getZigTypeAlignment() usize` at struct level
- at compile time, …
> feat: infer ZigType(ZT) from SSZType (ST)

- packages/common/src/hex.zig
- packages/common/src/root.zig
- packages/persistent-merkle-tree/README.md
- packages/persistent-merkle-tree/src/const.zig
- packages/persistent-merkle-tree/src/node.zig
- packages/persistent-merkle-tree/src/pool.zig
- packages/persistent-merkle-tree/src/root.zig
- packages/persistent-merkle-tree/src/tree.zig
- packages/persistent-merkle-tree/src/util.zig
- packages/persistent-merkle-tree/src/zero_hash.zig
an initial implementation of persistent-merkle-tree in zig following [typescript implementation](https://github.com/ChainSafe/ssz/tree/master/packages/persistent-merkle-tree)
The Merkle tree implementation uses a centralized node pool to manage all nodes efficiently. Nodes are created by the pool and reused to minimize memory allocations. When a node is no longer needed, you should call the `unref()` method, which decreases the node's reference count.
- Reference Counting: Each node tracks its usage with a reference count. When the count reaches zero, the node is returned to the pool.
- Reusability: Returned nodes are stored in the pool's LeafList and BranchList, making them available for reuse. This significantly reduces the need for frequent memory allocation during the application's …
> feat: persistent merkle tree initial implementation

- README.md
- To run tests in `test/int/type/container.zig`:
```
zig test --dep ssz --dep persistent_merkle_tree --dep util -Mroot=test/int/type/container.zig -Mutil=../common/src/root.zig -Mpersistent_merkle_tree=../persistent-merkle-tree/src/root.zig --dep util --dep persistent_merkle_tree -Mssz=src/root.zig
```
> fix: update commands to run tests in a single file

- .github/workflows/test.yml
- build.zig
- src/persistent_merkle_tree/gindex.zig
- src/persistent_merkle_tree/node_bench.zig
- src/ssz/root.zig
- src/ssz/tree_view.zig
- src/ssz/type/container.zig
- test/int/root.zig
- test/int/type/tree_view.zig
**Motivation**
- bring TreeView in Readme to unit test
- new `tree_view.zig` test under `test/int/type`, run it via `zig build test:int`
- move `TreeView.Data` to a separate struct because it's common for all TreeView types, otherwise get error: `error: expected type 'tree_view.TreeView(type.byte_vector.ByteVectorType(32)).Data', found 'tree_view.TreeView(type.container.FixedContainerType(type.tree_view.Checkpoint__struct_30115)).Data'`
- commit() does not work due to `setNodes()`, can look into it in another PR
> fix: unit test TreeView

- test/spec/download_spec_tests.zig
Currently, we try to allocate 16MB in the stack to a buffer when downloading spec test files.
When running on Mac, I got `illegal hardware instruction` because Mac's default stack size is 8MB and there is no way to reliably override this via `ulimit`.
Stack is often limited in size and we should be cautious when allocating large memory (quick google search says >1KB)on it.
> fix: use heap to download spec test

- build.zig
- zbuild.zon
Removes a dead types code generation step.
Done by editing `zbuild.zon` and running `zbuild sync`.
Closes #38
> deps: remove `types` library

- build.zig
- zbuild.zon
Closes #37
`bun-ffi` bindings are currently broken, causing noise in the output during build/test process. This PR removes them temporarily until they are fixed.
> deps: remove bun-ffi generation from `zbuild.zon`

- src/hashing/root.zig
- src/ssz/root.zig
`usingnamespace` is removed from the language as of `v0.15.0`: https://github.com/ziglang/zig/issues/20663
> chore: nuke all usage of `usingnamespace`

- src/ssz/type/bit_vector.zig
- src/ssz/type/list.zig
- src/ssz/type/root.zig
Tests were written but not imported in `root.zig`, so they were all not
being run.
> test: reintroduce sanity tests

- src/consensus_types/bellatrix.zig
- src/consensus_types/capella.zig
- src/consensus_types/deneb.zig
- src/consensus_types/electra.zig
Includes the following new types:
- `BlindedBeaconBlockBody`
- `BlindedBeaconBlock`
- `SignedBlindedBeaconBlock`
Unblocks https://github.com/ChainSafe/state-transition-z/issues/18
> feat: support blinded variants of beacon types

- src/ssz/root.zig
So the previous [PR](https://github.com/ChainSafe/ssz-z/pull/50) didn't fix it; we need to reimport again from the top-level `root.zig`.
To confirm: running `zig build test:ssz --summary all` shows 8 tests passing, remove the import and no tests will be ran.
> test(types): actually include types within tests

- src/ssz/type/bit_list.zig
- src/ssz/type/bit_vector.zig
- src/ssz/type/bool.zig
- src/ssz/type/byte_list.zig
- src/ssz/type/byte_vector.zig
- src/ssz/type/container.zig
- src/ssz/type/list.zig
- src/ssz/type/test_utils.zig
- src/ssz/type/uint.zig
- src/ssz/type/vector.zig
closes #31 
Some implementation details: in certain data types we can copy simply by assignment (like the primitives) but we must be careful to use the underlying `.clone()` api whenever possible especially when it comes to, for example, the container/array types.
> feat: implement `clone`

- src/persistent_merkle_tree/Node.zig
- src/persistent_merkle_tree/View.zig
- src/persistent_merkle_tree/root.zig
- noticed compile errors when using several functions
- use `refAllDeclsRecursive` in module-level test to ensure no obvious regressions
> fix: test ref all decls recursively in persistent_merkle_tree

- src/ssz/type/bit_list.zig
- src/ssz/type/bit_vector.zig
Missed the comment from @nazarhussain https://github.com/ChainSafe/ssz-z/pull/55#discussion_r2257017849 to use more efficient algorithm to loop through each bit.
> feat: more efficient `getTrueBitIndexes`

- src/ssz/tree_view.zig
- test/int/type/list_composite.zig
- test/int/type/tree_view.zig
**Motivation**
- it's not specified who owns `Data` in `TreeView` struct
Specify parent TreeView owns all Data recursively
- `getField()` only borrow Data so no need to deinit it, same to `getElement()`
- `setField()` transfer ownership of the child `value` TreeView and it returns the old child TreeView along with its ownership if any
- this is inspired by `fetchPut()` api of a HashMap because someone have to deinit the old child TreeView. It's up to the consumer how to use it.
- most of the time, I think consumer will just deinit the old TreeView.
> fix: parent TreeView owns data recursively

- src/persistent_merkle_tree/Node.zig
- src/persistent_merkle_tree/node_test.zig
- src/persistent_merkle_tree/root.zig
- test/int/type/tree_view.zig
**Motivation**
- cannot commit TreeView because setNodes() api was broken
- add `node_test.zig` to build process
- write new test and reproduce the issue in `persistent-merkle-tree`
Closes #60
> fix: setNodes api

- build.zig
- build.zig.zon
- zbuild.zon
- update snappy and hashtree dependency (no code change, just update of their zig build)
> chore: update dependencies

- src/ssz/type/bit_list.zig
As discussed in https://github.com/ChainSafe/ssz-z/pull/54#discussion_r2362545689
we should handle the shrinking case in `BitList` ie. calling resize() with `bit_len` shorter than current `bit_len`, to ensure trailing bits are always 0.
> fix: handle shrinking in BitList.resize()

- .github/workflows/test.yml
CI will run `zbuild sync` to make sure `build.zig` and `zbuild.zon` are sync'ed.
> feat: check if build.zig and zbuild.zon are sync'ed in CI 
